AWSTemplateFormatVersion: '2010-09-09'
Description: Task Manager Application - Frontend Only

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment
  
  JwtSecret:
    Type: String
    NoEcho: true
    Description: Secret key for JWT token validation
  
  AdminEmail:
    Type: String
    Description: Admin user's email address

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub TaskManager-UserPool-${Environment}
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
  
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub TaskManager-App-${Environment}
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
  
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub taskmanager-frontend-${Environment}-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
  
  WebsiteBucketName:
    Description: S3 bucket name for website
    Value: !Ref WebsiteBucket